//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 10.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !NO_EXPORT_APP_MAIN
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("do_low_error", "false");
    action();
  }
#endif

  // Main procedure 
  private void action()
  {

    // Local iconic variables 

    HObject ho_Image;


    // Local control variables 

    HTuple hv_AcqHandle;

    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);

    //Code generated by Image Acquisition 01
    HOperatorSet.OpenFramegrabber("DirectShow", 1, 1, 0, 0, 0, 0, "default", 8, "rgb", 
        -1, "false", "default", "HD USB Camera", 0, -1, out hv_AcqHandle);
    ho_Image.Dispose();
    HOperatorSet.GrabImage(out ho_Image, hv_AcqHandle);
    //Do something
    HOperatorSet.CloseFramegrabber(hv_AcqHandle);
    ho_Image.Dispose();

  }


}
#if !NO_EXPORT_APP_MAIN
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

